// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// estep_qvec_cpp
List estep_qvec_cpp(const NumericMatrix& B_mat, const NumericMatrix& p_mat, const NumericVector& prob_po, const IntegerVector& id_vec, const IntegerVector& k_vec, const int n_R0, const int m);
RcppExport SEXP _ordinal2phase_estep_qvec_cpp(SEXP B_matSEXP, SEXP p_matSEXP, SEXP prob_poSEXP, SEXP id_vecSEXP, SEXP k_vecSEXP, SEXP n_R0SEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type B_mat(B_matSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type p_mat(p_matSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type prob_po(prob_poSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type id_vec(id_vecSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type k_vec(k_vecSEXP);
    Rcpp::traits::input_parameter< const int >::type n_R0(n_R0SEXP);
    Rcpp::traits::input_parameter< const int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(estep_qvec_cpp(B_mat, p_mat, prob_po, id_vec, k_vec, n_R0, m));
    return rcpp_result_gen;
END_RCPP
}
// loglik_R0_cpp
double loglik_R0_cpp(const NumericVector& prob_po, const NumericMatrix& B_mat, const NumericMatrix& p_mat, const IntegerVector& id_vec, const int n_R0);
RcppExport SEXP _ordinal2phase_loglik_R0_cpp(SEXP prob_poSEXP, SEXP B_matSEXP, SEXP p_matSEXP, SEXP id_vecSEXP, SEXP n_R0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type prob_po(prob_poSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type B_mat(B_matSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type p_mat(p_matSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type id_vec(id_vecSEXP);
    Rcpp::traits::input_parameter< const int >::type n_R0(n_R0SEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_R0_cpp(prob_po, B_mat, p_mat, id_vec, n_R0));
    return rcpp_result_gen;
END_RCPP
}
// po_loglik_vec_cpp
NumericVector po_loglik_vec_cpp(const NumericVector& theta, const NumericMatrix& Xmat, const NumericMatrix& cumY, const double eps);
RcppExport SEXP _ordinal2phase_po_loglik_vec_cpp(SEXP thetaSEXP, SEXP XmatSEXP, SEXP cumYSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Xmat(XmatSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type cumY(cumYSEXP);
    Rcpp::traits::input_parameter< const double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(po_loglik_vec_cpp(theta, Xmat, cumY, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ordinal2phase_estep_qvec_cpp", (DL_FUNC) &_ordinal2phase_estep_qvec_cpp, 7},
    {"_ordinal2phase_loglik_R0_cpp", (DL_FUNC) &_ordinal2phase_loglik_R0_cpp, 5},
    {"_ordinal2phase_po_loglik_vec_cpp", (DL_FUNC) &_ordinal2phase_po_loglik_vec_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ordinal2phase(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
