# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estep_qvec_cpp <- function(B_mat, p_mat, prob_po, id_vec, k_vec, n_R0, m) {
    .Call('_ordinal2phase_estep_qvec_cpp', PACKAGE = 'ordinal2phase', B_mat, p_mat, prob_po, id_vec, k_vec, n_R0, m)
}

loglik_R0_cpp <- function(prob_po, B_mat, p_mat, id_vec, n_R0) {
    .Call('_ordinal2phase_loglik_R0_cpp', PACKAGE = 'ordinal2phase', prob_po, B_mat, p_mat, id_vec, n_R0)
}

#' Per-row proportional-odds log-likelihoods
#'
#' Computes per-observation log-likelihood contributions for a
#' proportional-odds model (ac = FALSE).
#'
#' @param theta Numeric vector of parameters:
#'   \eqn{(\alpha_1, \ldots, \alpha_{K-1}, \beta_1, \ldots, \beta_p)}.
#' @param Xmat Numeric matrix of predictors (n x p).
#' @param cumY Numeric matrix of cumulative indicators (n x K).
#' @param eps Small constant for numerical stability.
#' @return Numeric vector of length n with per-row log-likelihoods.
po_loglik_vec_cpp <- function(theta, Xmat, cumY, eps = 1e-12) {
    .Call('_ordinal2phase_po_loglik_vec_cpp', PACKAGE = 'ordinal2phase', theta, Xmat, cumY, eps)
}

